// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxunotnzpnchnzgordxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dW5vdG56cG5jaG56Z29yZHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDg0MTksImV4cCI6MjA2ODA4NDQxOX0.2nzcByU3v2FsS5_QHr024mERQHmOTbuARdLC__gnvYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});